name: FreezeMod
version: 1.1
main: net.techmastary.plugins.freezemod.FreezeMod
description: Freeze naughty cheaty players.
author: TechMastary
website: TechMastary.net
commands:
    freeze:
        usage: /<command> [player]
        description: Freeze players.
    unfreeze:
        usage: /<command> [player]
        description: Unfreeze players.
    freezeall:
        usage: /<command>
        description: Freeze everyone on the server
    unfreezeall:
        usage: /<command>
        description: Unfreeze everyone on the server.